/**
 * Task 7.4 — Public repo publication gate (req 09.8: two-person + secret-scan).
 *
 * Spec source: `flow/requirements/09-auth-multitenancy.md` §9.8:
 *   (a) Before any code/configuration reaches the public repository, a secret
 *       scan (gitleaks or equivalent) MUST pass.
 *   (b) The scan covers git history (not just the working tree).
 *   (c) Public-repo publication is a MANUAL, LOGGED, TWO-PERSON step — it is
 *       NOT automated.
 *
 * The gitleaks pre-commit/pre-push hooks + CI gate (Task 1.12) satisfy (a)+(b)
 * at the commit/push layer. THIS module wires requirement (c): it is the gate
 * a release operator must satisfy BEFORE a build/ref is pushed to the public
 * repo. A release is only permitted when:
 *   1. a fresh {@link SecretScanResult} with `passed === true` is attached, AND
 *   2. TWO DISTINCT PERSONS have signed off — the requester plus at least one
 *      other reviewer. A requester approving their own request does NOT count
 *      as the second person.
 *
 * Every successful release appends a tamper-evident entry to the audit
 * hash-chain (NFR-10) so the manual two-person step is logged and auditable.
 *
 * This is a pure, framework-free primitive (no DB, no git I/O) so it can be
 * unit-tested in isolation and later wired into a release API endpoint.
 */
import { randomUUID } from "node:crypto";
import {
  appendEntry,
  verifyChain,
  type AuditEntry,
  type ChainedAuditEntry,
  type ChainVerifyResult,
} from "@/lib/audit-hash-chain";

/** Outcome of a secret scan (gitleaks or equivalent) run prior to release. */
export interface SecretScanResult {
  /** Scanner that produced the result, e.g. `"gitleaks"`. */
  scanner: string;
  /** ISO-8601 timestamp the scan completed. */
  scannedAt: string;
  /** `true` when no secrets were found (req 09.8a gate). */
  passed: boolean;
  /** Number of findings (0 when clean). */
  findingsCount: number;
  /** Reference to the full report (CI run URL, artifact path, etc.). */
  reportRef: string | null;
}

/** A pending publication request — the "intent" half of the two-person step. */
export interface PublicationRequest {
  /** Stable request id (UUID). */
  id: string;
  /** Public repository URL the commit will be published to. */
  targetRepo: string;
  /** Target ref, e.g. `"main"`. */
  ref: string;
  /** Commit SHA being published. */
  commitSha: string;
  /** Person initiating the request (first of the two required persons). */
  requester: string;
  /** ISO-8601 timestamp the request was opened. */
  requestedAt: string;
}

/** A reviewer sign-off — the "second person" half of the two-person step. */
export interface PublicationApproval {
  /** Reviewer identity (MUST differ from the requester). */
  reviewer: string;
  /** ISO-8601 timestamp the approval was recorded. */
  approvedAt: string;
  /** Free-text review note. */
  comment: string | null;
}

/**
 * Full publication record: the request, attached approvals, the secret-scan
 * result, and (once released) release metadata. Immutable in spirit —
 * mutators return a new record.
 */
export interface PublicationRecord {
  request: PublicationRequest;
  approvals: PublicationApproval[];
  secretScan: SecretScanResult;
  /** ISO-8601 timestamp the release was executed, or `null` if not released. */
  releasedAt: string | null;
  /** Person who executed the release, or `null` if not released. */
  releasedBy: string | null;
}

/** Concrete reason a release was refused by {@link releasePublication}. */
export type PublicationRejectionReason =
  /** Fewer than two distinct persons signed off (req 09.8c two-person). */
  | "no-second-person"
  /** The attached secret scan did not pass (req 09.8a). */
  | "secret-scan-failed";

/** Outcome of {@link releasePublication}. */
export interface PublicationGateResult {
  /** `true` when the release was permitted and recorded. */
  released: boolean;
  /** Rejection reason, or `null` when released. */
  reason: PublicationRejectionReason | null;
  /** The (possibly released) record. */
  record: PublicationRecord;
  /**
   * Audit-chain entries produced by this release. Empty until a release
   * succeeds; a successful release appends exactly one entry.
   */
  auditEntries: ChainedAuditEntry[];
}

/**
 * Input for {@link requestPublication} — the requester-supplied fields. The
 * request `id` and `requestedAt` are generated by the gate.
 */
export interface RequestPublicationInput {
  targetRepo: string;
  ref: string;
  commitSha: string;
  requester: string;
  secretScan: SecretScanResult;
}

/**
 * Open a publication request. The record starts pending: no approvals, no
 * release. The attached {@link SecretScanResult} is carried with the record so
 * the release gate can re-assert it passed at release time.
 */
export function requestPublication(input: RequestPublicationInput): PublicationRecord {
  return {
    request: {
      id: randomUUID(),
      targetRepo: input.targetRepo,
      ref: input.ref,
      commitSha: input.commitSha,
      requester: input.requester,
      requestedAt: new Date().toISOString(),
    },
    approvals: [],
    secretScan: input.secretScan,
    releasedAt: null,
    releasedBy: null,
  };
}

/**
 * Record a reviewer approval. Returns a NEW record (does not mutate input).
 *
 * @throws when the reviewer is the requester — a person cannot self-approve to
 *         satisfy the two-person rule (req 09.8c).
 */
export function addApproval(
  record: PublicationRecord,
  approval: PublicationApproval,
): PublicationRecord {
  if (approval.reviewer === record.request.requester) {
    throw new Error(
      "publication gate: self-approval is not allowed — the two-person rule (req 09.8c) requires a second distinct reviewer",
    );
  }
  return { ...record, approvals: [...record.approvals, approval] };
}

/**
 * Distinct reviewer identities (excludes the requester by construction thanks
 * to {@link addApproval}).
 */
function distinctApprovers(record: PublicationRecord): string[] {
  return Array.from(new Set(record.approvals.map((a) => a.reviewer)));
}

/**
 * Evaluate the publication gate and, if satisfied, mark the record released
 * and append a tamper-evident audit-chain entry.
 *
 * Gate (req 09.8):
 *   1. `record.secretScan.passed === true`  — secret scan passed (09.8a).
 *   2. `distinctApprovers(record).length >= 1` — a second distinct person
 *      has approved (09.8c two-person; the requester is the first).
 *
 * The check order is deliberate: a secret leak is the more dangerous failure,
 * so it is reported first.
 */
export function releasePublication(
  record: PublicationRecord,
  release: { releasedBy: string },
): PublicationGateResult {
  if (!record.secretScan.passed) {
    return {
      released: false,
      reason: "secret-scan-failed",
      record,
      auditEntries: [],
    };
  }

  const approvers = distinctApprovers(record);
  if (approvers.length < 1) {
    return {
      released: false,
      reason: "no-second-person",
      record,
      auditEntries: [],
    };
  }

  const releasedAt = new Date().toISOString();
  const released: PublicationRecord = {
    ...record,
    releasedAt,
    releasedBy: release.releasedBy,
  };

  // Build the audit entry capturing two-person + scan evidence (req 09.8c
  // "manual, logged" — NFR-10 tamper-evident chain).
  const details = JSON.stringify({
    targetRepo: record.request.targetRepo,
    ref: record.request.ref,
    commitSha: record.request.commitSha,
    requester: record.request.requester,
    approvers,
    secretScan: {
      scanner: record.secretScan.scanner,
      passed: record.secretScan.passed,
      findingsCount: record.secretScan.findingsCount,
      reportRef: record.secretScan.reportRef,
    },
  });
  const entry: AuditEntry = {
    projectId: `publication:${record.request.targetRepo}`,
    action: "publication.release",
    entityType: "publication",
    entityId: record.request.id,
    details,
    author: release.releasedBy,
    createdAt: releasedAt,
  };
  const auditEntries = appendEntry([], entry);

  return { released: true, reason: null, record: released, auditEntries };
}

/**
 * Verify a publication audit-chain slice for tampering/gaps. Mirrors
 * {@link verifyChain} but is exported from this module so callers that consume
 * publication records have a stable, co-located verifier without reaching into
 * the audit primitive directly.
 */
export function verifyPublicationChain(
  chain: ReadonlyArray<ChainedAuditEntry>,
): ChainVerifyResult {
  return verifyChain(chain);
}
